version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache for Ruby dependencies

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - run:
          name: Run codeclimate
          command: |
            CODECLIMATE_REPO_TOKEN=631eb88aeefb155fa6b0e97978598692a502051d1d59e0f2c4a4a7cc5b0f522c bundle exec codeclimate-test-reporter
